### ISSUE TITLE
Add descriptions inline to the XML.

### ISSUE THREAD

**Issue by eric-jahn** [auntbertha/openeligibility#10]
I'd recommend using <xs:documentation xml:lang="en"/> tags to inline the documentation at http://openeligibility.org/glos/ into the schema.  Then everything's in one tidy place.  Otherwise, to populate the definitions into a db table, we'd have to scrape the site :( .  Thank you!

**Comment by erineg1** [comment]
Hi Eric--

Realize it's been a long time. I was able to update the xml to include the descriptions inline. Please check it out, and let me know if you have any suggestions. We are also trying to keep the openeligibility.org site in synce (although we may just scrap it and replace it with github's fancy website features). Don't know enough about it yet.

Regardless, you should be able to get all the descriptions within the xml! Once you're okay with it, just let me know and I can close / add to this issue.
