### ISSUE TITLE
Add codes to each identifier

### ISSUE THREAD

**Issue by eric-jahn** [auntbertha/openeligibility#11]
It'll be more compact to just transmit the codes around, instead of the text.  I think something like numeric + decimal would be great, like 1.12.1.1 for the four levels would be easiest.  I don't think alphanumeric would add anything, but curious to hear what the rest of you think.

**Comment by erineg1** [comment]
Hey Eric--

Also wanted to let you know that with this last release, we added codes with a nomenclature that should work going forward. You'll note that we added a new attribute: id and title. With id being in the format of XXX-XX-XX (depending on how many levels deep the taxonomy is). 

Always looking for suggestions. It's there now, would love your thoughts!
