### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ckoppelman** [auntbertha/openeligibility#28]
What is the license for this taxonomy?  Right now, it's assumed this is copyrighted, but the "open" in openeligibility implies otherwise.  What is correct?

**Comment by greggish** [comment]
@ckoppelman the Open Eligibility website indicates: Human Services Taxonomy by Aunt Bertha, Inc. is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License. It would be good to have that indicated here in Github as well...

**Comment by motinda** [comment]
Added the license notation to the README.
