### ISSUE TITLE
Question about classification of domestic violence shelters

### ISSUE THREAD

**Issue by Noah-T** [auntbertha/openeligibility#29]
We're working on mapping some of Boston Children's Hospital's service categories into the Open Eligibility taxonomy. One category we have is for domestic violence shelters. I feel pretty comfortable associating it with these categories: 

101-06-01,Help Escape Violence,101-06,Immediate Safety 
and
101-06,Immediate Safety,101,Emergency 

I'm less sure about this one:
101-06-02,Safe Housing,101-06,Immediate Safety

Does anyone have thoughts on what the safe housing category is intended for and whether or not it would be appropriate for domestic violence shelters? Any thoughts/comments are greatly appreciated. Thanks!

**Comment by ckoppelman** [comment]
According to the [glossary](http://openeligibility.org/glos/#S):

**Safe Housing** — Safe and secure residential facility in an undisclosed location where victims of abuse can remain safe from the abuser.

I think DV and similar shelters are exactly that.

**Comment by Noah-T** [comment]
Great. Thank you for your answer!

It may be helpful to link directly to the glossary or even include it in the repo for future users.
